/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import beans.Aluno;
import beans.Matricula;
import beans.Professor;
import dao.MatriculaDao;
import dao.AlunoDao;
import dao.ProfessorDao;
import javax.swing.JOptionPane;
import java.sql.Date;

/**
 *
 * @author laboratorio
 */
public class View extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(View.class.getName());

    /**
     * Creates new form pessoaView
     */
    public View() {
        initComponents();
        carregarDados();
    }
    
    private void carregarDados() {
    aluno.removeAllItems();
    AlunoDao dao = new AlunoDao();
    for (String nome : dao.listarAlunos()) {
        aluno.addItem(nome);
    }
    
    professor.removeAllItems();
    ProfessorDao dao1 = new ProfessorDao();
    for (String nome : dao1.listaProfessores()) {
        professor.addItem(nome);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        nome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        saveAluno = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        curso = new javax.swing.JComboBox<>();
        txtIdade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        disciplina = new javax.swing.JComboBox<>();
        saveProfessor = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        aluno = new javax.swing.JComboBox<>();
        professor = new javax.swing.JComboBox<>();
        saveMatricula = new javax.swing.JButton();
        deleteProfessor = new javax.swing.JButton();
        deleteAluno = new javax.swing.JButton();
        searchAluno = new javax.swing.JButton();
        searchProfessor = new javax.swing.JButton();
        updateAluno = new javax.swing.JButton();
        updateProfessor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome");

        jLabel2.setText("Curso");

        saveAluno.setText("Salvar Aluno");
        saveAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAlunoActionPerformed(evt);
            }
        });

        jLabel3.setText("Idade");

        curso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "Ciencia da computacao", "Jogos", "Medicina", "Psicologia" }));

        jLabel4.setText("Disciplina");

        disciplina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Etica", "Libras", "Algoritmo A", "algoritmo B" }));
        disciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disciplinaActionPerformed(evt);
            }
        });

        saveProfessor.setText("Salvar Professor");
        saveProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveProfessorActionPerformed(evt);
            }
        });

        jLabel5.setText("Aluno");

        jLabel6.setText("Professor");

        aluno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        professor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        saveMatricula.setText("Matricular");
        saveMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMatriculaActionPerformed(evt);
            }
        });

        deleteProfessor.setText("Excluir Professor");
        deleteProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProfessorActionPerformed(evt);
            }
        });

        deleteAluno.setText("Excluir Aluno");
        deleteAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAlunoActionPerformed(evt);
            }
        });

        searchAluno.setText("Consultar aluno");
        searchAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAlunoActionPerformed(evt);
            }
        });

        searchProfessor.setText("Consultar professor");
        searchProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchProfessorActionPerformed(evt);
            }
        });

        updateAluno.setText("Atualizar aluno");
        updateAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateAlunoActionPerformed(evt);
            }
        });

        updateProfessor.setText("Atualizar professor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(saveMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(disciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(professor, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(aluno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(updateProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(searchProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(updateAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(searchAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(saveAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deleteProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saveProfessor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(curso, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)))
                        .addContainerGap(17, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(saveAluno)
                                .addGap(185, 185, 185))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(148, 148, 148)
                                        .addComponent(searchAluno)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(updateAluno)
                                        .addGap(40, 40, 40)
                                        .addComponent(searchProfessor))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(177, 177, 177)
                                                .addComponent(deleteAluno)
                                                .addGap(40, 40, 40)
                                                .addComponent(deleteProfessor))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(40, 40, 40)
                                                .addComponent(saveProfessor)))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(updateProfessor)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(disciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addGap(13, 13, 13)
                        .addComponent(aluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(professor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)))
                .addComponent(saveMatricula)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void saveAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAlunoActionPerformed
        Aluno a = new Aluno();
        a.setNome(nome.getText());
        a.setIdade(Integer.parseInt(txtIdade.getText().trim()));
        a.setCurso(curso.getSelectedItem().toString());

        AlunoDao dao = new AlunoDao();
        dao.insert(a);

        JOptionPane.showMessageDialog(this, "Aluno salvo com sucesso!");
        carregarDados();
        nome.setText("");
        txtIdade.setText("");
    }//GEN-LAST:event_saveAlunoActionPerformed

    private void disciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disciplinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disciplinaActionPerformed

    private void saveMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMatriculaActionPerformed
    AlunoDao dao = new AlunoDao();
    int idAluno = dao.buscarIdAluno(aluno.getSelectedItem().toString());
    
    ProfessorDao dao1 = new ProfessorDao();
    int idProfessor = dao1.buscarIdProfessor(professor.getSelectedItem().toString());
     
    Matricula m = new Matricula();
    m.setAlunoId(idAluno);
    m.setProfessorId(idProfessor);
    m.setData_matricula(new Date(System.currentTimeMillis()));

    MatriculaDao dao2 = new MatriculaDao();
    dao2.insert(m);

    JOptionPane.showMessageDialog(this, "Aluno matriculado com sucesso!");
    }//GEN-LAST:event_saveMatriculaActionPerformed

    private void saveProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveProfessorActionPerformed
        Professor p = new Professor();
        p.setNome(nome.getText());
        p.setIdade(Integer.parseInt(txtIdade.getText().trim()));
        p.setDisciplina(disciplina.getSelectedItem().toString());

        ProfessorDao dao = new ProfessorDao();
        dao.insert(p);

        JOptionPane.showMessageDialog(this, "Professor salvo com sucesso!");
        carregarDados();
        nome.setText("");
        txtIdade.setText("");
    }//GEN-LAST:event_saveProfessorActionPerformed

    private void deleteAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAlunoActionPerformed
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o aluno?", "Exclusão", JOptionPane.YES_NO_OPTION);
        AlunoDao dao = new AlunoDao();
        int idAluno = dao.buscarIdAluno(aluno.getSelectedItem().toString());
        
        if (resposta == JOptionPane.YES_OPTION){
            dao.deleteAluno(idAluno);
            JOptionPane.showMessageDialog(this, "Aluno deletado com sucesso!");
        }else{
            JOptionPane.showMessageDialog(this, "Exclusão cancelada com sucesso!");
        }
        carregarDados();
        nome.setText("");
        txtIdade.setText("");
        
    }//GEN-LAST:event_deleteAlunoActionPerformed

    private void deleteProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProfessorActionPerformed
  
    }//GEN-LAST:event_deleteProfessorActionPerformed

    private void searchAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAlunoActionPerformed
        AlunoDao dao = new AlunoDao();
        int idAluno = dao.buscarIdAluno(aluno.getSelectedItem().toString());
        
        Aluno a = dao.getAluno(idAluno);
        if(a == null){
           nome.setText("");
           txtIdade.setText("");
           JOptionPane.showMessageDialog(this, "Pessoa não encontrada");
        }else{
           nome.setText(a.getNome());
           txtIdade.setText(String.valueOf(a.getIdade()));
           curso.setSelectedItem(a.getCurso());
        }
    }//GEN-LAST:event_searchAlunoActionPerformed

    private void updateAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateAlunoActionPerformed
            AlunoDao dao = new AlunoDao();
            int idAluno = dao.buscarIdAluno(aluno.getSelectedItem().toString());
            Aluno a = new Aluno();
            a.setNome(nome.getText());
            a.setIdade(Integer.parseInt(txtIdade.getText().trim()));
            a.setCurso(curso.getSelectedItem().toString());
            
            a.setId(idAluno);
            
            dao.updateAluno(a);

            JOptionPane.showMessageDialog(this, "Aluno atualizado com sucesso!");
            carregarDados();
            nome.setText("");
            txtIdade.setText("");
    }//GEN-LAST:event_updateAlunoActionPerformed

    private void searchProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchProfessorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new View().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> aluno;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> curso;
    private javax.swing.JButton deleteAluno;
    private javax.swing.JButton deleteProfessor;
    private javax.swing.JComboBox<String> disciplina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nome;
    private javax.swing.JComboBox<String> professor;
    private javax.swing.JButton saveAluno;
    private javax.swing.JButton saveMatricula;
    private javax.swing.JButton saveProfessor;
    private javax.swing.JButton searchAluno;
    private javax.swing.JButton searchProfessor;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JButton updateAluno;
    private javax.swing.JButton updateProfessor;
    // End of variables declaration//GEN-END:variables
}
